### ISSUE TITLE
Require ROIs for wells

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#16]
Some processing needs to happen on the whole well, e.g. 2D segmentation of MIPs. If segmentation is done for the whole well, downstream processing (e.g. measurements) should also happen for the whole well (see https://github.com/fractal-analytics-platform/fractal/issues/69#issuecomment-1231270833).

This has led to workarounds of e.g. the measurement task taking a flag for `whole_well`. I think it would be easier to define well ROIs (a table with a single ROI per well). Then, a user could just select the correct ROI from the ROI tables (e.g. have the selection between well, FOV and organoids). The tasks then don't need to worry about handling two separate input cases, because everything comes as a ROI.

Benefits:
- Simpler task logic
- Could be helpful for some registration parts, e.g. one could register a well, keep all the image data even if not all cycles are available for edge pixels, but define a ROI of just the shared region as the new `well` ROI.

Downsides:
- Overhead of creating well ROIs and managing them, even though we could just figure out what the whole well is based on the metadata in the zarr file

**Comment by tcompa** [comment]
This was introduced with https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/3d9e1988367232b12bc3e9e881da0c596d0d2232 (and a few more refinements later). In the current version:
* Another table is written in `tables`, named `well_ROI_table`;
* `yokogawa_to_zarr` directly reads the well bounding box from this table, instead of using `get_ROIs_bounding_box` (which was doing something quite similar);
* CAVEAT: this means that we are back with indices (rather than column names), as in the following block. In fact the part of the names should be shifted to the `prepare_well_ROI_table`, but at that point the same decision should be taken for `prepare_FOV_ROI_table` --> let's discuss this flexibility somewhere else.
```python
    adata_well = read_zarr(f"{zarrurl}/tables/well_ROI_table")
    well_indices = convert_ROI_table_to_indices(
        adata_well, full_res_pxl_sizes_zyx=pxl_size
    )
    max_z = well_indices[0][1]
    max_y = well_indices[0][3]
    max_x = well_indices[0][5]
```
* In `image_labeling`, we now take an ROI-table argument
```python
    ROI_table_name: str = "FOV_ROI_table",
```
* We can now deprecate the `image_labeling_whole_well` function (let's first make sure that we remove it from all tests/examples).

**Comment by jluethi** [comment]
Great :)
Can you open a separate issue for the `get_ROIs_bounding_box` discussion? Not sure I follow why there would be different functions for well & FOV (and later also organoids?). Couldn't a refactored function then just use the `ROI_table_name` input, then process the corresponding table?
Also, let's use that issue to get away again from the index-based accessing of ROI positions. That's fine for internal use (e.g. for getting to the demo), but we'll want to generalize that eventually :)
