### ISSUE TITLE
[napari-workflows] Restrict scope of wrapper?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#174]
With @mfranzon, we are not 100% happy with the shape the napari-workflow wrapper task is taking.

Some constraints on the valid workflows are already in-place (e.g. `level>0` is only allowed for "labeling" worfklows), other constraints are being discussed (e.g. "IF there are N>=1 label outputs, THEN EITHER there are image inputs (assumed to have the same shape) OR there is one and only one label input.", see #161), additional parameters may have to be specified (e.g. `relabeling`, see #138). And we just scratched the surface of how general these workflows can be, since they are just dask graphs after all.

The main question is: how much will we want to support arbitrary workflows? To be as general as possible, we will likely have to include a long list of constraints or additional parameters. The current use cases (mainly labeling/measurement) are close to being fully covered, but we don't know what will come next. It's likely that an arbitrary user-provided workflow will not satisfy some of our constraints.

A possible way out (to be explored) is to strongly limit the scope of the supported workflows. The first idea coming to mind is to only accept workflows with arbitrary number of inputs but a single output, so that it would be simpler to know how to handle it. We don't fully appreciate how severe this constraint would be, but at least our guess is that it would streamline the cases-handling a bit.

An alternative option is obviously to shift responsibility towards the user as much as possibly, by asking a possibly long list of parameters and then handling everything with `if/else` branches. Also here: to be understood how far this would go.

Let's keep this in mind, and discuss when appropriate.

**Comment by jluethi** [comment]
> The main question is: how much will we want to support arbitrary workflows? To be as general as possible, we will likely have to include a long list of constraints or additional parameters. The current use cases (mainly labeling/measurement) are close to being fully covered, but we don't know what will come next. It's likely that an arbitrary user-provided workflow will not satisfy some of our constraints.

Very good point and good discussion. My top-level feeling: 
1) We should support a core set of workflow types. 
2) We should have checks to catch when something doesn't fit into that setting
3) Depending on the issues that would come up, we either raise Exceptions about workflows not being supported (yet) [if we think things may break or behavior will lead to wrong results] or warnings if we're fairly sure that it should run through.

How far will we ever need to support arbitrary workflows? Good question. Potentially very general.
How far should we aim for with the current implementation of napari workflows: Let's limit our scope. We don't currently support image -> image workflows and I think that's out of scope for the time being. We don't support table inputs so far, but that's also out of scope for the time being I'd think.

> A possible way out (to be explored) is to strongly limit the scope of the supported workflows. The first idea coming to mind is to only accept workflows with arbitrary number of inputs but a single output, so that it would be simpler to know how to handle it. We don't fully appreciate how severe this constraint would be, but at least our guess is that it would streamline the cases-handling a bit.

I'm generally in favor of limiting our scope for how we build the napari workflow wrapper now, because it's hard to fully see all potential edge cases and we want to start somewhere. As to what is a reasonable limit:
If we limit workflows to single outputs, that can be quite a constraint and suboptimal on IO for the default workflow. Many default workflows may include: Process image a bit, then label, then make some measurements. If we need to separate the labeling & the measurements (technically feasible), that means we will have many quite short workflows and a somewhat confusing user experience.
I can see a case for limiting to 1 label output and n tables with measurements. In that case, the relabeling should become a bit simpler: If there is a label output, we relabel that and can relabel all the measurements by whatever label transformation is calculated on the labels.
What we would exclude with that limit are workflows where different objects are segmented (e.g. organoids and then cells), but I think there is a much better case to be made to have them run in separate workflows.

------

Big picture strategy:
We find an implementation with reasonable constraints to keep the scope in check. When necessary in the future, we may relax a specific constraint once we found a way to handle its complexities.
I'd like the initial level to be workflows from image / labels to at least (1) label + (n) measurements output, because then we should cover a broad set of use-cases for the napari workflows.
And we'll raise Exceptions with clear statements of the limits if a workflow doesn't fit our scope. I'm happy to write a user-guide as to what is allowed and how users should structure typical use-cases once the scope is well defined.

**Comment by tcompa** [comment]
> I'd like the initial level to be workflows from image / labels to at least (1) label + (n) measurements output, because then we should cover a broad set of use-cases for the napari workflows. And we'll raise Exceptions with clear statements of the limits if a workflow doesn't fit our scope.

All right, that seems a specific-enough scope, thanks

**Comment by tcompa** [comment]
Closing for now, as there is no action required. Let's come back here in the future if needed.
