### ISSUE TITLE
Update test dataset

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#240]
While working on #239, I though a few updates of the test datasets would be useful.

The first one is that we should put a new zarr on zenodo, complying with the new rules (that is, the omero channels should always include also a `wavelength_id` attribute).

**Comment by jluethi** [comment]
Once this is in place, I can update the examples we have so that they produce the new output and we can just update the zenodo dataset with a new version (already did this once for one of them).

**Comment by tcompa** [comment]
For testing, this is currently taken care of with a workaround in a fixture: https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/e3690ef255ca200f6833b326932f79ce0abfef0c

**Comment by tcompa** [comment]
> Once this is in place, I can update the examples we have so that they produce the new output and we can just update the zenodo dataset with a new version (already did this once for one of them).

(of course this is the way to go..)

**Comment by jluethi** [comment]
@tcompa I updated the main 2 datasets on Zenodo. Because the data changed, they also get a new identifier. They can now be found here:

Tiny: https://zenodo.org/record/7674545
2x2: https://zenodo.org/record/7674571

I ran the tiny at higher cellpose labeling resolution than before. So if you update this in the test, check whether it still matches well (are we testing for getting the exact same data actually? Could anyway be tricky, not sure whether cellpose is pixel-perfect reproducible).

I used those workflows to generate the datasets:
Tiny: https://github.com/fractal-analytics-platform/fractal-demos/tree/1a82185bc0132095275ea012155e04b666c33ba1/examples/01_cardio_tiny_dataset
2x2: https://github.com/fractal-analytics-platform/fractal-demos/tree/1a82185bc0132095275ea012155e04b666c33ba1/examples/02_cardio_small

**Comment by tcompa** [comment]
Thanks!

To do:
- [ ] Update the way they are used in the tests; that is, remove the fixture introduced in https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/e3690ef255ca200f6833b326932f79ce0abfef0c.

**Comment by tcompa** [comment]
For the record: we do not use the multiplexing dataset in the CI.

> are we testing for getting the exact same data actually?

We aren't. The zarr dataset are mostly used as a valid starting point for additional processing steps, but we do not check that tasks produce exactly the same output.
