### ISSUE TITLE
Have an example of Fractal running on a public dataset

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#29]
Let's have at least one example in the main Fractal repo that runs on a public dataset (see https://github.com/fractal-analytics-platform/fractal/issues/163) and produces relevant outputs that would be fitting for a Fractal demo.

**Comment by jluethi** [comment]
I uploaded the 2x2, 10Z test case as a Zenodo dataset here: https://zenodo.org/record/7057076

@tcompa Let me know if you have a smaller test set already ready or in mind. I can annotate it with the relevant metadata information about the staining etc and upload it to Zenodo :)

**Comment by tcompa** [comment]
> @tcompa Let me know if you have a smaller test set already ready or in mind. I can annotate it with the relevant metadata information about the staining etc and upload it to Zenodo :)

I'd like to have one which is as small as possible.
What about a single channel (dapi?), two Z planes (somewhere in the middle of the Z stack), and two FOVs instead of four? That would be 4 images, which seems reasonably small to me.

**Comment by tcompa** [comment]
Note that the goals of having some data on zenodo are (from high to low priority):
1. Building a demo with publicly-available (and reliable) data, instead of using local copies of the same (which could get out of sync, if anything needs to be fixed e.g. in the metadata files).
2. Using a tiny dataset within CI. Depending on the download time (*), we could either always include these tests in the CI or keep them as optional.
3. Preparing a heavy integration test on a reasonably large dataset (to be run on the cluster, and not as part of the standard CI).

Given these goals, [zenodo-get](https://github.com/dvolgyes/zenodo_get) seems to be good enough in downloading all data for a zenodo record (where "good enough" stands for "only download files if they are not already present, and check their md5 checksum"). I'm adding it as an optional dependency, by now.


(*) From a couple of tests, I'm expecting the download time for the four-images dataset to be ~10 seconds, which eventually would be fine to be part of the CI..

**Comment by jluethi** [comment]
@tcompa Thanks for the list of priorities, I agree with the order. Let's aim for 1 & 2 for the moment, 3 is more a long-term goal.

The tiny dataset is now also available on Zenodo: https://zenodo.org/record/7059515
Let's include it in our tests, it's just 27 MB to download and should give the confirmation that the tests run on some real data.

I also put it on our share for the moment (`/data/active/fractal/3D/PelkmansLab/CardiacMultiplexing/Cycle1_tinyTestSet`), but the data on Zenodo should be the relevant reference.

**Comment by tcompa** [comment]
With https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/1627e117238772f4bd036df4732615f4ebe2a96a, we have a first example running on real-data (which is a mirror of the client/server one, in the `fractal` repository).

With the tiny dataset, this first example runs on a local machine in a few seconds (but it will be a few minutes when adding labeling, depending on `labeling_level`).

We should include a couple more tasks, and then this issue can be closed.

**Comment by tcompa** [comment]
Examples are running both on the tiny dataset and on the 2x2-FOVs one, see https://github.com/fractal-analytics-platform/fractal-server/issues/4#issuecomment-1243407277.

I'm closing this. Let's open more specific issues if needed.
