### ISSUE TITLE
Helper pre/post-processing functions to load masked arrays and then cleanup after processing

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#334]
Requires:
* #333 

Here is a sketch of our discussion with @jluethi (it's all to be re-checked):
```python
def masked_array_preprocessing(image_array, primary_label_array=None, label_value=None, use_masks=False):
    if not use_masks:
        return image_array, None
    else:
        background = primary_label_array != label_value
        image_array[background] = 0
        return image_array, background

def masked_array_postprocessing(new_label_array, old_label_array, use_masks=False):
    if not use_masks:
        return None
    else:
        new_label_array[background] = old_label[background]
        return new_label

# -------------------

# as part of cellpose task:

if "label" in ROI_table.obs.columns:
    use_masks = True
else:
    use_masks = False

for ROI in ROIs:
    if use_masks:
        # load the appropriate primary-label array (note: this can be moved inside the preprocessing function, if we also propagate the ROI indices)
        # load the current version of the secondary-label array that we are computing
    image_array, background = masked_array_preprocessing(image_array, primary_label_array=None, label_value=None, use_masks=False)
    # .. call cellpose segmentation
    # .. call postprocessing function
```

Also to keep in mind:
- [x] Check matching levels of labels. Upscaling of primary labels is acceptable, downscaling is out of scope.

[to be reviewed/updated tomorrow]

**Comment by jluethi** [comment]
Sounds great! :)

**Comment by tcompa** [comment]
Basic feature added with https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/d4611cdc29dcf7238585e9fe54b82a938df335f5 (still 100% preliminary).

**Comment by tcompa** [comment]
As of 2d37864527258c27ab9ca72d421f0c7418ce5f19, we now can also work with different resolution levels, e.g. organoid labels produced at level 3, and then nuclei-in-organoids segmentation at level 2.

**Comment by tcompa** [comment]
I also clarified quite a bit the pre/post-processing functions, see new docstrings to get a glimpse of them:

![Screenshot from 2023-03-08 16-10-51](https://user-images.githubusercontent.com/3862206/223751082-4b773af7-06ba-48ec-bfd8-f3a6ae20087c.png)
![Screenshot from 2023-03-08 16-11-04](https://user-images.githubusercontent.com/3862206/223751128-37ba9090-0ea1-43c0-a157-e2cd12dd7ef4.png)

**Comment by jluethi** [comment]
Great additions to the docstring!

Suggestions on variable naming:
`preprocess_cellpose_input`:
`primary_label_path`: is this needed mid-term when it can be read from the metadata? If so, then something like `mask_label_path` would be nice
`ROI_table_obs`: See question below
`ROI_index`: `ROI label`? (we're using the label column, not the index, right?)

`postprocess_cellpose_output`
Not sure about `modified_array` and `original_array`, but also no better ideas. The docstrings for them are clear.


Other questions: 
1. Would this work for dask arrays as well? Could be useful for some other applications of the masked loading, but not needed for our cellpose implementation I'd guess

2. For my understanding: In this mode, it needs to read every chunk that's being written to before it writes to it for each ROI, right? Because we only keep them in memory for as long we're processing that region, then we drop it. Acceptable trade-off, just wanting to check

3. Do we need the `region` in other parts of the function (other than read & write => pre & post)? Otherwise, we could abstract this into the function and just give the function the ROI_table + label, it calculates both the slices as well as gets the label value from obs. 

4. When generalizing, can we remove the 3D/4D constraints for the arrays?

**Comment by tcompa** [comment]
Briefly, as a trace of our discussion.

> 1. Would this work for dask arrays as well? Could be useful for some other applications of the masked loading, but not needed for our cellpose implementation I'd guess

It is not trivial, because of unknown shapes of dynamically-masked objects. Let's postpone this discussion.

>     2. For my understanding: In this mode, it needs to read every chunk that's being written to before it writes to it for each ROI, right? Because we only keep them in memory for as long we're processing that region, then we drop it. Acceptable trade-off, just wanting to check

That's indeed the way we're doing it.

>     3. Do we need the `region` in other parts of the function (other than read & write => pre & post)?

Yes, in the `to_zarr` part.

>     4. When generalizing, can we remove the 3D/4D constraints for the arrays?

Ref #340

**Comment by tcompa** [comment]
And thanks for the naming comments
