### ISSUE TITLE
Update anndata (version and import source of `write_elem`)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#427]
See https://anndata.readthedocs.io/en/stable/release-notes/index.html

**Comment by jluethi** [comment]
Would be great to evaluate this. I think the `write_elem` has now also moved out of the experimental part, thus maybe we can ignore anndata's torch interactions with that. I'll test this briefly for the md converter, where `write_elem` in experimental has been making some issues.

**Comment by jluethi** [comment]
Actually, the more important part will be this: 
Let's switch to using the `write_elem` function as `ad._io.specs.write_elem`, instead of importing it from experimental. It has worked in my tests for the MD, let's try also on the Fractal side. 

The big benefit: `ad._io.specs` does not import torch => no more anndata worries about torch.

See: https://github.com/jluethi/fractal-faim-hcs/issues/1

**Comment by tcompa** [comment]
> Let's switch to using the `write_elem` function as `ad._io.specs.write_elem`, instead of importing it from experimental. It has worked in my tests for the MD, let's try also on the Fractal side.
> 
> The big benefit: `ad._io.specs` does not import torch => no more anndata worries about torch.

Fully agreed.

For the record:
* The `write_elem` function is exactly the same, since the `experimental` module simply imports from `_io.specs` (see https://github.com/scverse/anndata/blob/main/anndata/experimental/__init__.py, where it also imports torch).
* The `_io` module is still "experimental" and could change without notice, so I'm setting anndata version to be `anndata = ">=0.8.0,<=0.9.1`. We can incrementally include other versions after testing.
