### ISSUE TITLE
[docs] Define clear task structure

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#7]
Define a clear structure of how our tasks need to be written for future tasks. The best would be a small example task that shows the structure and input/output handling

**Comment by tcompa** [comment]
In the docs, there should be a couple of example tasks:
* A global task (acting on nothing);
* A task which will be parallelized over wells.

Each task should have its full call signature, i.e. it should include both fractal-specific and task-specific arguments. And we should also show how a task can be added to the manifest.


This issue is currently on hold, waiting for the ongoing major refactor of the server/client architecture.

**Comment by tcompa** [comment]
Close in favor of https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/151
