### ISSUE TITLE
Relax Pydantic V1 constraint from `==1.10.16` to `>=1.10.16`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#768]
cc @lorenzocerrone

**Comment by lorenzocerrone** [comment]
I will quickly open a pr for this in the afternoon

**Comment by lorenzocerrone** [comment]
As you mentioned @tcompa during the last pydantic PR review, there is no strong reason to pic `pydantic>=2.6.3`. 

Since I needed to rework the version check anyway, I want to test if the manifest creation is compatible with all pydantic 2* versions. The answer is yes; from version `2.0.0` the manifest building works and has no diffs from the current version in main. 

After my tests I don't see any reasons to keep the runtime check.
Should I remove it? And just leave the simple version constraint pydantic >=1.10.16?

**Comment by tcompa** [comment]
> After my tests I don't see any reasons to keep the runtime check.
> Should I remove it? And just leave the simple version constraint pydantic >=1.10.16?

I agree.
If we ever hit an issue with some manifest building coming from e.g. pydantic 2.3, we can quickly re-introduce the runtime version constraint. But note that this would only happen if someone is pinning pydantic=2.3 in their own package.
