### ISSUE TITLE
OME-Zarr parsing for sparsely recorded fields

### ISSUE THREAD

**Issue by gusqgm** [fractal-analytics-platform/fractal-tasks-core#8]
Can .zarr containers contain only the data present in the fields that actually contain data within a well? This would require the parsing of the Yokogawa experiment to be able to extract (z,y,x) stage positions, assigning corresponding values to corresponding fields. 

As a first step, we need to parse the x,y,width and height from the metadata file from yokogawa experiments, and one example is found in the [yokogawa_image_collection_task](https://github.com/fmi-basel/job-system-workflows/blob/4162be86f1f09d9153809c7c2026904bd432b62d/src/gliberal_workflows/tasks/yokogawa_image_collection_task/versions/version_0_4.py#L156) from the _Liberali Workflows_ repository. All metadata is saved in the so-called _mlf_frame_ file

On the simplest case, the sparse fields would still fall onto a grid pattern, so parsing should then be able to extrapolate the size of the entire grid, and be able to place the recorded fields in the correct grid positions.

Currently Drogon creates an overview of 0's where fields were not recorded, filling up the gaps. The saved overviews also comprise of a mask overview which is used for retaining only the imaged fields for processing and avoid overfilling memory.

One interesting question here is whether OME-Zarr can actually deal with sparse field grids, meaning that the empty fields would remain empty, or would be assigned to same-sized stacks filled with 0's.

**Comment by jluethi** [comment]
To facilitate tackling this issue:
1) We need to fix https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/13 to use the metadata instead of row & col parameters (let's not throw away the row & col logic: It's useful to have, but should not be the default and should not be used when there is metadata available).
2) Let's add to this to make sure it can also handle a search-first (grid-based): See Search-first 1) here https://github.com/fractal-analytics-platform/fractal/issues/213
3) Let's test it on a larger search first dataset: See Search-first 2)

Let's discuss 1) in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/13

For 2)
Careful, this dataset has different channels. Until we have fixed https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/5, let's make sure we specify them manually
When the processing works correctly, it should look like this (see also above from @gusqgm ): 
![A06-overview_MIP_labeled](https://user-images.githubusercontent.com/18033446/189859692-e01d26d6-42bf-4d77-8e7a-9b2f6ed02c0b.png)

Still like a grid, but not all parts have content. We will need to ensure that we build an empty array of the correct size initially to be able to fill in all the positions. And we can't make assumptions based on the count of FOVs or just look at first and last (otherwise, we're not tackling part 3)). => We will need to look at the metadata table, find the top left and bottom right corner based on all the x & y position and the image sizes.

**Comment by tcompa** [comment]
> We will need to look at the metadata table, find the top left and bottom right corner based on all the x & y position and the image sizes.

At the moment, this happens based on the FOV-ROI indices, rather than on the x/y physical positions. In the parsing task there is a block like
```python
        adata = read_zarr(f"{zarrurl}/tables/FOV_ROI_table")
        fov_rois = convert_ROI_table_to_indices(adata, full_res_pxl_sizes_zyx=pxl_size)

        max_x = max(roi[5] for roi in fov_rois)
        max_y = max(roi[3] for roi in fov_rois)
        max_z = max(roi[1] for roi in fov_rois)
        [...]
        canvas = da.zeros((max_z, max_y, max_x), dtype=sample.dtype, chunks=(1, chunk_size_y, chunk_size_x))
```
where 5,3,1 are the indices corresponding to `end_z,end_y,end_x`, as in `roi=[start_z, end_z, start_y, end_y, start_x, end_x]`. Note that the `max_z` part is a bit redundant, as all FOV should have the same number of Z planes.

@jluethi, do you notice anything unexpected in the way we are doing it?

**Comment by jluethi** [comment]
I'd be a bit cautious with using an index-based selection of the columns here. It assumes that the ordering of the AnnData ROI tables will always be the same. While our system should be consistent here, we may want to support other OME-Zarr files that contain tables with the same information, but the order of columns shouldn't be a part of that spec
=> Can we switch to selecting columns based on their names in `var`? Also, can we implement that such that we have default column names, but those can be overwritten as an optional input? (because the spec for how those columns are named may change in the future).

It's good to have `max_z`, as it may vary between wells, see e.g. the test case `/data/active/fractal/3D/PelkmansLab/CardiacMultiplexing/Cycle1_5x5_10wells` (https://github.com/fractal-analytics-platform/fractal/issues/213). Mostly, I expect FOVs within a well to be consistent, but I'm not even sure that will always be the case and is not required by the specification.

Given that it handles the 2x2 case, it seems to be able to handle negative coordinates. The 2x2 case has X positions like `X="-1448.3"`, so that's good :)
The general canvas definition and max position finding looks good to me

**Comment by tcompa** [comment]
As of https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/5c1410edb6ca628084991e1250adf43b0f805660, the new function `get_ROIs_bounding_box` by @mfranzon and me is meant to take care of this last comment.

Missing features:
1. The column names can be overwritten, but at the moment this is not exposed to the user.
2. By now we are not shifting ROI positions (to make them start from zero), because our AnnData tables are already shifted (that takes place in `prepare_FOV_ROI_table`). We probably need to be more general, if we want to read zarr files produced outside fractal, but I'd say we can postpone the implementation of this feature.

**Comment by jluethi** [comment]
The `/data/active/fractal/Liberali/1_well_15_fields_20_planes_SF_w_errors/D10_R1/220304_172545_220304_175557` search first dataset is processed successfully with the current Fractal version:
<img width="1650" alt="Bildschirmfoto 2022-09-27 um 21 40 57" src="https://user-images.githubusercontent.com/18033446/192627103-66ba49c0-58df-4f0a-91b3-68275216cb2a.png">

<img width="1650" alt="Bildschirmfoto 2022-09-27 um 21 40 40" src="https://user-images.githubusercontent.com/18033446/192627126-608d3fc5-021f-47f9-89c3-a04e3b0e73ab.png">

The other 2 search first test cases appear to have some issues in the metadata parsing (https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/109 & https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/110), but that's most likely unrelated to the search first part of it.

I'll need to have a brief check whether the segmentation and measurements have worked correctly on this dataset. After that, we can close this issue
